### ISSUE TITLE
Significant performance issues at larger comparisons

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#42] opened 2016-10-20 21:20 UTC
When larger comparisons - either in point number (less common), or chromosome number (more common) - are performed, serious performance issues are present yielding renderer unusable. Issues usually manifesting in two major areas:
1. Extremely long rendering time, currently causing browser to hang and sometimes resulting in tabs/web browsers crashing. We can likely background this process, but slow loading time is still undesirable to end user. (i.e. an analysis with a 12-chr species (well assembled) vs a 100k-chr (poorly assembled) species can take >5min to load)
2. Slow interactivity - zooming/interaction slows down in rapidly as number of elements increases, and eventually becomes unusable .

**Example:** https://genomevolution.org/r/lzq9
Note, this is only a medium-large analysis, some we have been receiving (under restricted data) might yield 10x the elements

**Comment by seanastephens** [comment] 2016-10-22 23:24
I've reproduced this locally. The slowdown comes because of the large number of chromosomes for organism 19927. There are 12585 of them, and many are very short; below is the distribution of lengths.

```
10^0-10^1: 2
10^1-10^2: 38
10^2-10^3: 11996
10^3-10^4: 502
10^4-10^5: 36
10^5-10^6: 3
10^6-10^7: 0
10^7-10^8: 7
```

Many of these chromosomes have names of the form
```
Scaffold000001
```

None of the files that we have been using to test while developing include anywhere near this many chromosomes (the max among those is 695), and I missed this scenario. The performance problem occurs because we add one DOM node for each chromosome (the line that separates it from its neighbors), and 10,000+ DOM nodes is a lot.

@asherkhb are all of these chromosomes meaningful? I can filter out the small ones based on some arbitrary length threshold (say, `length < 100,000`), but you might know of something more intelligent we can do. If the small ones are important, I can look into dynamic filtering based on zoom level.

**Comment by asherkhb** [comment] 2016-10-23 15:24
Yea, I'd missed this sceneario too, so unfortunately we didn't provide a sample analysis like this (but after release users started sending me questions about them). 

It is important that we keep those smaller chromosomes, as some users genomes are stored like that and users are still looking for information within them. Maybe a dynamic filtering, or is it possible to somehow combine the DOM nodes for those lines?

**Comment by seanastephens** [comment] 2016-10-24 01:56
> Maybe a dynamic filtering, or is it possible to somehow combine the DOM nodes for those lines?

That's sort of what I mean by dynamic filtering -- we wouldn't add DOM nodes for chromosomes that aren't relevant at a given zoom level.

cf053bc9f adds a temporary solution that just filters out some of the small chromosomes. It is indistinguishable from no filtering at the maximum zoom level and performs reasonably well: http://hdc-arizona.github.io/synteny-vis/#z. I can look into a dynamic filtering solution later this week.

@asherkhb Can you estimate the maximum number of chromosomes we can expect to see? Rough guess is fine. You also mentioned performance problems for large point numbers; if you have a specific example please post a link.

**Comment by asherkhb** [comment] 2016-12-19 22:47
Ooops, just saw the outstanding question -

It's difficult to actually set a maximum number in terms of what we might ever see, but I am pretty sure we have 250,000 limit per genome currently.

**Comment by seanastephens** [comment] 2016-12-19 22:53
Thanks. Two follow ups:

You mentioned performance problems with large numbers of points -- do you have a comparison that exhibits this? I'd like to add it as a test case I can work on locally (and fix whatever the problem is).

**Comment by asherkhb** [comment] 2016-12-19 22:56
I believe it may actually be just large chromosome number's that is responsible, and points are probably fine.

**Comment by seanastephens** [comment] 2016-12-19 23:04
Closing this until the simple solution (unconditional filtering of small chromosomes) becomes an issue, since a complete, zoom-aware filtering solution is quite a bit more complicated for marginal benefit.

**Closed by seanastephens** 2016-12-19 23:04 UTC

**Comment by asherkhb** [comment] 2016-12-19 23:37
what exactly was the solution? Will it filter out all small chromosomes and never display them?

**Comment by seanastephens** [comment] 2016-12-20 00:01
Yes, everything below length 10000 will never be displayed.

Right now there is a maximum zoom level, and at that maximum zoom, you can't even tell that these chromosomes were filtered out.

**Comment by asherkhb** [comment] 2016-12-20 17:24
Sounds good. In the future we may need to make some changes to accomodate people working on small virus genomes, Maybe something along the lines of either..
* if < 100 pieces, never filter
or
* if total length < 1000000, stop filtering

This will work fine for now though!
